return {
	intelephense = require("plugins.lsp.settings.intelephense"),
	-- phpactor = require("plugins.lsp.settings.phpactor"),
	ts_ls = {},
	html = {},
	tailwindcss = require("plugins.lsp.settings.tailwindcss"),
	lua_ls = require("plugins.lsp.settings.lua-ls"),
	graphql = {},
	prismals = {},
	docker_compose_language_service = {},
	dockerls = {},
	yamlls = require("plugins.lsp.settings.yamlls"),
	eslint = {},
	bashls = {},
	gopls = require("plugins.lsp.settings.gopls"),
	jqls = {},
	jsonls = require("plugins.lsp.settings.jsonls"),
	basedpyright = {},
	terraformls = {},
	jinja_lsp = require("plugins.lsp.settings.jinja-lsp"),
	ansiblels = require("plugins.lsp.settings.ansiblels"),
	gh_actions_ls = {},
	stylelint_lsp = {},
	tombi = {},
}
